"""create initial tables

Revision ID: 171fd750526d
Revises: 
Create Date: 2026-07-12 20:41:10.229476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171fd750526d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celulares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('referencia', sa.String(length=50), nullable=False),
    sa.Column('imei', sa.String(length=20), nullable=False),
    sa.Column('valor_costo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_comercial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'Disponible'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imei')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    op.create_table('publicidad_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo_campana', sa.String(length=100), nullable=False),
    sa.Column('url_imagen', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('celular_nuevo_id', sa.Integer(), nullable=False),
    sa.Column('valor_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['celular_nuevo_id'], ['celulares.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('tasa_interes_mensual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cuotas_totales', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'Activo'"), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venta_id')
    )
    op.create_table('detalle_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('valor_abono_efectivo', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('valor_abono_transferencia', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('valor_retoma_id', sa.Integer(), nullable=True),
    sa.Column('monto_financiado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['valor_retoma_id'], ['celulares.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venta_id')
    )
    op.create_table('cuotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_interes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'Pendiente'"), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuotas')
    op.drop_table('detalle_pagos')
    op.drop_table('creditos')
    op.drop_table('ventas')
    op.drop_table('publicidad_banners')
    op.drop_table('clientes')
    op.drop_table('celulares')
    # ### end Alembic commands ###
