"""add tipo_venta a ventas

Revision ID: 2632a29dbef4
Revises: 24fed4682696
Create Date: 2026-07-23 17:04:39.511200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2632a29dbef4'
down_revision: Union[str, None] = '24fed4682696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('tipo_venta', sa.String(length=20), server_default=sa.text("'Credito'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'tipo_venta')
    # ### end Alembic commands ###
