"""valor_comercial nullable en celulares

Revision ID: c1d5057d95da
Revises: 2632a29dbef4
Create Date: 2026-07-27 17:26:57.286739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d5057d95da'
down_revision: Union[str, None] = '2632a29dbef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('celulares', 'valor_comercial',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('celulares', 'valor_comercial',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###
